site_name: OpenVidu Docs
pages:
- ['home/index.md','What is OpenVidu?']
- ['tutorials/index.md','Tutorials', 'Intro']
- ['tutorials/openvidu-hello-world.md','Tutorials', 'openvidu-hello-world']
- ['tutorials/openvidu-insecure-js.md','Tutorials', 'openvidu-insecure-js']
- ['tutorials/openvidu-insecure-angular.md','Tutorials', 'openvidu-insecure-angular']
- ['tutorials/openvidu-js-java.md','Tutorials', 'openvidu-js-java']
- ['tutorials/openvidu-mvc-java.md','Tutorials', 'openvidu-mvc-java']
- ['tutorials/openvidu-js-node.md','Tutorials', 'openvidu-js-node']
- ['tutorials/openvidu-mvc-node.md','Tutorials', 'openvidu-mvc-node']
- ['tutorials/openvidu-getaroom.md','Tutorials', 'openvidu-getaroom']
- ['reference-docs/openvidu-browser.md','Reference Documentation', 'openvidu-browser API']
- ['reference-docs/openvidu-java-client.md','Reference Documentation', 'openvidu-java-client API']
- ['reference-docs/openvidu-node-client.md','Reference Documentation', 'openvidu-node-client API']
- ['reference-docs/REST-API.md','Reference Documentation', 'REST  API']
- ['reference-docs/openvidu-artifacts.md','Reference Documentation', 'OpenVidu Artifacts']
- ['deployment/deploying-demos-aws.md','Deployment', 'Deploying OpenVidu Demos on AWS (TUTORIAL)']
- ['deployment/deploying-aws.md','Deployment', 'Deploying OpenVidu Server and your app on AWS']
- ['deployment/deploying-ubuntu.md','Deployment', 'Deploying OpenVidu as a native service']
- ['deployment/custom-certificate.md','Deployment', 'Using your own certificate']
- ['developing/index.md','Contribute', 'Developing OpenVidu']
- ['troubleshooting/index.md','Troubleshooting / FAQ']
theme: readthedocs
repo_url: https://github.com/OpenVidu/openvidu.io-docs
